#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-survminer
Version  : 0.4.9
Release  : 2
URL      : https://cran.r-project.org/src/contrib/survminer_0.4.9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/survminer_0.4.9.tar.gz
Summary  : Drawing Survival Curves using 'ggplot2'
Group    : Development/Tools
License  : GPL-2.0
Requires: R-broom
Requires: R-dplyr
Requires: R-ggplot2
Requires: R-ggpubr
Requires: R-ggtext
Requires: R-gridExtra
Requires: R-magrittr
Requires: R-maxstat
Requires: R-purrr
Requires: R-rlang
Requires: R-scales
Requires: R-survMisc
Requires: R-tibble
Requires: R-tidyr
BuildRequires : R-broom
BuildRequires : R-dplyr
BuildRequires : R-ggplot2
BuildRequires : R-ggpubr
BuildRequires : R-ggtext
BuildRequires : R-gridExtra
BuildRequires : R-magrittr
BuildRequires : R-maxstat
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-scales
BuildRequires : R-survMisc
BuildRequires : R-tibble
BuildRequires : R-tidyr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
and 'ready-to-publish' survival curves with the 'number at risk' table
    and 'censoring count plot'. Other functions are also available to plot 
    adjusted curves for `Cox` model and to visually examine 'Cox' model assumptions.

%prep
%setup -q -n survminer

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713979970

%install
export SOURCE_DATE_EPOCH=1713979970
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/survminer/DESCRIPTION
/usr/lib64/R/library/survminer/INDEX
/usr/lib64/R/library/survminer/Meta/Rd.rds
/usr/lib64/R/library/survminer/Meta/data.rds
/usr/lib64/R/library/survminer/Meta/features.rds
/usr/lib64/R/library/survminer/Meta/hsearch.rds
/usr/lib64/R/library/survminer/Meta/links.rds
/usr/lib64/R/library/survminer/Meta/nsInfo.rds
/usr/lib64/R/library/survminer/Meta/package.rds
/usr/lib64/R/library/survminer/Meta/vignette.rds
/usr/lib64/R/library/survminer/NAMESPACE
/usr/lib64/R/library/survminer/NEWS.md
/usr/lib64/R/library/survminer/R/survminer
/usr/lib64/R/library/survminer/R/survminer.rdb
/usr/lib64/R/library/survminer/R/survminer.rdx
/usr/lib64/R/library/survminer/data/Rdata.rdb
/usr/lib64/R/library/survminer/data/Rdata.rds
/usr/lib64/R/library/survminer/data/Rdata.rdx
/usr/lib64/R/library/survminer/doc/Informative_Survival_Plots.R
/usr/lib64/R/library/survminer/doc/Informative_Survival_Plots.Rmd
/usr/lib64/R/library/survminer/doc/Informative_Survival_Plots.html
/usr/lib64/R/library/survminer/doc/Playing_with_fonts_and_texts.R
/usr/lib64/R/library/survminer/doc/Playing_with_fonts_and_texts.Rmd
/usr/lib64/R/library/survminer/doc/Playing_with_fonts_and_texts.html
/usr/lib64/R/library/survminer/doc/Specifiying_weights_in_log-rank_comparisons.R
/usr/lib64/R/library/survminer/doc/Specifiying_weights_in_log-rank_comparisons.Rmd
/usr/lib64/R/library/survminer/doc/Specifiying_weights_in_log-rank_comparisons.html
/usr/lib64/R/library/survminer/doc/ggforest-show-interactions-hazard-ratio.R
/usr/lib64/R/library/survminer/doc/ggforest-show-interactions-hazard-ratio.Rmd
/usr/lib64/R/library/survminer/doc/ggforest-show-interactions-hazard-ratio.html
/usr/lib64/R/library/survminer/doc/index.html
/usr/lib64/R/library/survminer/help/AnIndex
/usr/lib64/R/library/survminer/help/aliases.rds
/usr/lib64/R/library/survminer/help/paths.rds
/usr/lib64/R/library/survminer/help/survminer.rdb
/usr/lib64/R/library/survminer/help/survminer.rdx
/usr/lib64/R/library/survminer/html/00Index.html
/usr/lib64/R/library/survminer/html/R.css
/usr/lib64/R/library/survminer/tests/testthat.R
/usr/lib64/R/library/survminer/tests/testthat/test-ggsurvtable.R
